use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let shader_dir = Path::new("src/shaders");

    let mut glsl_files: Vec<PathBuf> = fs::read_dir(shader_dir)
        .expect("Cannot read shader directory")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("glsl"))
        .collect();

    // Watch each individual shader file so edits trigger recompilation.
    // Directory-level watches may not detect file content changes on Windows.
    for glsl in &glsl_files {
        println!("cargo:rerun-if-changed={}", glsl.display());
    }

    // Sort for deterministic output ordering.
    glsl_files.sort();

    let mut generated = String::from("// Auto-generated by gg_engine/build.rs — do not edit.\n\n");

    let profile = env::var("PROFILE").unwrap_or_default();

    for glsl_path in &glsl_files {
        let stem = glsl_path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("Shader file has no stem");

        let source = fs::read_to_string(glsl_path)
            .unwrap_or_else(|e| panic!("Cannot read {}: {e}", glsl_path.display()));

        let shader_type = detect_shader_type(&source);

        match shader_type {
            ShaderType::Graphics => {
                let (vert_src, frag_src) = split_glsl_source(&source, glsl_path);
                let has_offscreen = source.contains("#ifdef OFFSCREEN");

                let vert_tmp = out_dir.join(format!("{stem}.vert"));
                let frag_tmp = out_dir.join(format!("{stem}.frag"));
                fs::write(&vert_tmp, &vert_src)
                    .unwrap_or_else(|e| panic!("Cannot write {}: {e}", vert_tmp.display()));
                fs::write(&frag_tmp, &frag_src)
                    .unwrap_or_else(|e| panic!("Cannot write {}: {e}", frag_tmp.display()));

                // Offscreen shaders are compiled with -DOFFSCREEN; plain shaders without defines.
                let defines: &[&str] = if has_offscreen { &["OFFSCREEN"] } else { &[] };

                let vert_spv = out_dir.join(format!("{stem}_vert.spv"));
                let frag_spv = out_dir.join(format!("{stem}_frag.spv"));
                compile_glslc(&vert_tmp, &vert_spv, &profile, defines);
                compile_glslc(&frag_tmp, &frag_spv, &profile, defines);

                validate_spirv(&vert_spv);
                validate_spirv(&frag_spv);

                let upper = stem.to_uppercase();
                generated.push_str(&format!(
                    "pub const {upper}_VERT_SPV: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{stem}_vert.spv\"));\n"
                ));
                generated.push_str(&format!(
                    "pub const {upper}_FRAG_SPV: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{stem}_frag.spv\"));\n"
                ));

                // For shaders with #ifdef OFFSCREEN, also compile a swapchain variant (no defines).
                if has_offscreen {
                    let sw_vert_spv = out_dir.join(format!("{stem}_swapchain_vert.spv"));
                    let sw_frag_spv = out_dir.join(format!("{stem}_swapchain_frag.spv"));
                    compile_glslc(&vert_tmp, &sw_vert_spv, &profile, &[]);
                    compile_glslc(&frag_tmp, &sw_frag_spv, &profile, &[]);

                    validate_spirv(&sw_vert_spv);
                    validate_spirv(&sw_frag_spv);

                    let sw_upper = format!("{upper}_SWAPCHAIN");
                    generated.push_str(&format!(
                        "pub const {sw_upper}_VERT_SPV: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{stem}_swapchain_vert.spv\"));\n"
                    ));
                    generated.push_str(&format!(
                        "pub const {sw_upper}_FRAG_SPV: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{stem}_swapchain_frag.spv\"));\n"
                    ));
                }
            }
            ShaderType::Compute => {
                let comp_src = extract_compute_source(&source, glsl_path);

                let comp_tmp = out_dir.join(format!("{stem}.comp"));
                fs::write(&comp_tmp, &comp_src)
                    .unwrap_or_else(|e| panic!("Cannot write {}: {e}", comp_tmp.display()));

                let comp_spv = out_dir.join(format!("{stem}_comp.spv"));
                compile_glslc(&comp_tmp, &comp_spv, &profile, &[]);
                validate_spirv(&comp_spv);

                let upper = stem.to_uppercase();
                generated.push_str(&format!(
                    "pub const {upper}_COMP_SPV: &[u8] = include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{stem}_comp.spv\"));\n"
                ));
            }
        }
    }

    let shaders_rs = out_dir.join("shaders.rs");
    fs::write(&shaders_rs, &generated).unwrap_or_else(|e| panic!("Cannot write shaders.rs: {e}"));
}

// ---------------------------------------------------------------------------
// Shader type detection
// ---------------------------------------------------------------------------

enum ShaderType {
    Graphics,
    Compute,
}

fn detect_shader_type(source: &str) -> ShaderType {
    for line in source.lines() {
        let trimmed = line.trim();
        if trimmed == "#type compute" {
            return ShaderType::Compute;
        }
        if trimmed == "#type vertex" || trimmed == "#type fragment" {
            return ShaderType::Graphics;
        }
    }
    // Default to graphics if no type markers found (shouldn't happen).
    ShaderType::Graphics
}

// ---------------------------------------------------------------------------
// Source extraction
// ---------------------------------------------------------------------------

/// Split a combined `.glsl` source into (vertex_source, fragment_source).
fn split_glsl_source(source: &str, path: &Path) -> (String, String) {
    let mut vert_lines: Vec<&str> = Vec::new();
    let mut frag_lines: Vec<&str> = Vec::new();
    let mut current: Option<&str> = None;

    for line in source.lines() {
        let trimmed = line.trim();
        if trimmed == "#type vertex" {
            current = Some("vertex");
        } else if trimmed == "#type fragment" {
            current = Some("fragment");
        } else {
            match current {
                Some("vertex") => vert_lines.push(line),
                Some("fragment") => frag_lines.push(line),
                _ => {} // content before any #type marker is ignored
            }
        }
    }

    if vert_lines.is_empty() {
        panic!(
            "Shader '{}' is missing a '#type vertex' section",
            path.display()
        );
    }
    if frag_lines.is_empty() {
        panic!(
            "Shader '{}' is missing a '#type fragment' section",
            path.display()
        );
    }

    (vert_lines.join("\n"), frag_lines.join("\n"))
}

/// Extract compute shader source from a `#type compute` marked file.
fn extract_compute_source(source: &str, path: &Path) -> String {
    let mut comp_lines: Vec<&str> = Vec::new();
    let mut in_compute = false;

    for line in source.lines() {
        let trimmed = line.trim();
        if trimmed == "#type compute" {
            in_compute = true;
        } else if in_compute {
            comp_lines.push(line);
        }
    }

    if comp_lines.is_empty() {
        panic!(
            "Shader '{}' has '#type compute' marker but no source code",
            path.display()
        );
    }

    comp_lines.join("\n")
}

// ---------------------------------------------------------------------------
// Compilation & Validation
// ---------------------------------------------------------------------------

/// Invoke `glslc` to compile a GLSL source file to SPIR-V.
/// Adds `-O` optimization flag when building in release mode.
/// Preprocessor `defines` are passed as `-DNAME` flags.
fn compile_glslc(input: &Path, output: &Path, profile: &str, defines: &[&str]) {
    let mut cmd = Command::new("glslc");
    cmd.arg("--target-env=vulkan1.2");

    for def in defines {
        cmd.arg(format!("-D{def}"));
    }

    if profile == "release" || profile == "dist" {
        cmd.arg("-O");
    }

    let status = cmd
        .arg(input)
        .arg("-o")
        .arg(output)
        .status()
        .unwrap_or_else(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                panic!(
                    "\n\n\
                     ERROR: 'glslc' not found in PATH.\n\
                     Install the Vulkan SDK from https://vulkan.lunarg.com/ and ensure\n\
                     the SDK's bin directory is in your PATH.\n\n"
                );
            }
            panic!("Failed to run glslc: {e}");
        });

    if !status.success() {
        panic!(
            "glslc failed to compile '{}'. Check GLSL syntax.",
            input.display()
        );
    }
}

/// Run spirv-val on a compiled SPIR-V file. Skips silently if spirv-val is not installed.
fn validate_spirv(spv_path: &Path) {
    match Command::new("spirv-val").arg(spv_path).output() {
        Ok(output) => {
            if !output.status.success() {
                let stderr = String::from_utf8_lossy(&output.stderr);
                panic!(
                    "spirv-val validation failed for '{}':\n{}",
                    spv_path.display(),
                    stderr
                );
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            // spirv-val not installed, skip validation.
            println!("cargo:warning=spirv-val not found, skipping SPIR-V validation");
        }
        Err(e) => {
            println!("cargo:warning=Failed to run spirv-val: {e}");
        }
    }
}
